In [1]:
import numpy as np

In [12]:
a2 = np.array([[1,2,3],
    [4,5,6]
               
])
a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
])

In [14]:
a2.shape,a3.shape
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [32]:
a2 = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]           
])
a2.shape,a3.shape

((3, 3), (2, 3, 3))

In [33]:
a2*a3

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]]])

In [29]:
a2 = np.array([[1,2,3],
    [4,5,6]
               
])
a2 = a2.reshape(2,3,1)
a2

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [30]:
a2*a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [20]:
a2 + a3

array([[[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]],

       [[14, 15, 16],
        [18, 19, 20],
        [22, 23, 24]]])

In [21]:
a3 - a2

array([[[ 0,  1,  2],
        [ 2,  3,  4],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 8,  9, 10],
        [10, 11, 12]]])

In [22]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
    [4,5,6]
               
])

In [23]:
a1 + a2

array([[2, 4, 6],
       [5, 7, 9]])

In [24]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [25]:
a1.shape,a2.shape

((3,), (2, 3))

In [34]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a2.sort()

None


In [42]:
a1 = np.array([1,3,6,5,7,8,4,2,9])

b1 = sorted(a1)
b1

[1 3 6 5 7 8 4 2 9]


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
np.argsort(a1)

array([0, 7, 1, 6, 3, 2, 4, 5, 8], dtype=int64)

In [68]:
a1 = np.random.randint(100,size=(1000,20,100))
a1.sort()

In [56]:
%timeit np.argsort(a1,kind='heapsort')
%timeit np.argsort(a1,kind='mergesort')
%timeit np.argsort(a1,kind='quicksort')
%timeit np.argsort(a1,kind='stable')
%timeit np.argsort(a1)

71.2 ms ± 971 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
50.6 ms ± 385 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
52.4 ms ± 597 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
49.3 ms ± 609 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
51.8 ms ± 943 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [73]:
a = np.array([9, 3, 1, 3, 4, 3, 6])
b = np.array([4, 6, 9, 2, 1, 8, 7])
print("Sütun1, Sütun2")
for (i,j) in zip(a,b):
    print(i,'           ',j)
ind = np.lexsort((b,a))
print("Sıralanmış İndis:",ind)

Sütun1, Sütun2
9             4
3             6
1             9
3             2
4             1
3             8
6             7
Sıralanmış İndis: [2 3 1 5 4 6 0]
